### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TopOneOfTopOne**
merge this shit

### CODE REVIEW

**Comment by Arwic** [comment]
Updated the reamdme with more info

**Comment by TopOneOfTopOne** [comment]
lmao trim the last two are not features, they are dependencies. Features are mostly positive, dependencies are mostly negative but that depends on how you look at it. Another way to look at it is features come from **your** code  anything else is not a feature. 💌  💌  lol

**Comment by Arwic** [comment]
There

**Comment by TopOneOfTopOne** [comment]
nice dank readme baby

**Pull request closed without merging**
